/**
 * Created by W-Q on 2017/9/21.
 */
export const TOPHEIGHT = 'TOPHEIGHT';
export const NAVPATHCHANGE = 'NAVPATHCHANGE';
export const UPDATELOADINGSTATUS = 'UPDATELOADINGSTATUS';
export const PUBLICLEVELID = 'PUBLICLEVELID';
export const PERMISSIONLEVELID = 'PERMISSIONLEVELID';
export const X2STORELEVELID = 'X2STORELEVELID';
export const STORETREELIST = 'STORETREELIST';
export const SHOWSTORETREE = 'SHOWSTORETREE';
export const TREEARR = 'TREEARR';
