/**
 * Created by W-Q on 2017/9/21.
 */
export const TOPHEIGHT = 'TOPHEIGHT';
export const NAVPATHCHANGE = 'NAVPATHCHANGE';
export const UPDATELOADINGSTATUS = 'UPDATELOADINGSTATUS';
export const PUBLICLEVELID = 'PUBLICLEVELID';
export const PERMISSIONLEVELID = 'PERMISSIONLEVELID';
export const X1STORELEVELID = 'X1STORELEVELID';
export const X2STORELEVELID = 'X2STORELEVELID';
export const STORETREELIST = 'STORETREELIST';
export const SHOWSTORETREE = 'SHOWSTORETREE';
export const TREEARR = 'TREEARR';
export const RUNNINGSTATELEVELID = 'RUNNINGSTATELEVELID';
export const PRINTCONFLEVELID = 'PRINTCONFLEVELID';
export const PUSHSTATELEVELID = 'PUSHSTATELEVELID';
export const BUSINESSCONFLEVELID = 'BUSINESSCONFLEVELID';
export const PERMISSIONTREE = 'PERMISSIONTREE';
export const BUSINESSCONFTREE = 'BUSINESSCONFTREE';
export const PUSHSTATETREE = 'PUSHSTATETREE';
export const RUNNINGSTATETREE = 'RUNNINGSTATETREE';
export const PRINTCONFTREE = 'PRINTCONFTREE';
export const X1STORETREE = 'X1STORETREE';
export const X2STORETREE = 'X2STORETREE';
export const PUBLICTREE = 'PUBLICTREE';
export const SCATTERMAPTREE = 'SCATTERMAPTREE';
export const SCATTERMAPTREELEVELID = 'SCATTERMAPTREELEVELID';

